SELECT
SUM(case when c.status_type_id=1 then 1 ELSE 0 END) AS `total_certified`,
SUM(case when c.status_type_id=1 AND c.expiration_date > CURDATE() then 1 ELSE 0 END) AS `total_certified_active`,
SUM(case when c.status_type_id=1 AND c.expiration_date <= CURDATE() then 1 ELSE 0 END) AS `total_certified_expired`,
SUM(case when c.status_type_id=1 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male`,
SUM(case when c.status_type_id=1 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female`,
(SELECT COUNT(*) AS `total_certified_multiple_certifications` FROM (SELECT COUNT(c.id) AS `count` FROM certifications c WHERE c.status_type_id=1 GROUP BY c.practitioner_id HAVING COUNT(c.id) > 1) as `total_certified_multiple_certifications`) as `total_certified_multiple_certifications`,
SUM(case when c.status_type_id=1 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino`,
SUM(case when c.status_type_id=1 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign`,

SUM(case when c.status_type_id=1 AND c.modality_class_id=1 then 1 ELSE 0 END) AS `total_certified_cma`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=2 then 1 ELSE 0 END) AS `total_certified_cama`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=3 then 1 ELSE 0 END) AS `total_certified_ca`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=4 then 1 ELSE 0 END) AS `total_certified_caa`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=69 then 1 ELSE 0 END) AS `total_certified_vap`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=8 then 1 ELSE 0 END) AS `total_certified_cch`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=11 then 1 ELSE 0 END) AS `total_certified_chp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=36 then 1 ELSE 0 END) AS `total_certified_rhp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=12 then 1 ELSE 0 END) AS `total_certified_cmh`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=37 then 1 ELSE 0 END) AS `total_certified_ch`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=17 then 1 ELSE 0 END) AS `total_certified_cmn`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=18 then 1 ELSE 0 END) AS `total_certified_cnp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=21 then 1 ELSE 0 END) AS `total_certified_co`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=22 then 1 ELSE 0 END) AS `total_certified_ctmcp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=39 then 1 ELSE 0 END) AS `total_certified_ccmd`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=26 then 1 ELSE 0 END) AS `total_certified_catmt`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=27 then 1 ELSE 0 END) AS `total_certified_ctmt`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=28 then 1 ELSE 0 END) AS `total_certified_cahp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=29 then 1 ELSE 0 END) AS `total_certified_caap`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=30 then 1 ELSE 0 END) AS `total_certified_caamp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=31 then 1 ELSE 0 END) AS `total_certified_camp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=32 then 1 ELSE 0 END) AS `total_certified_calp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=33 then 1 ELSE 0 END) AS `total_certified_calt`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=34 then 1 ELSE 0 END) AS `total_certified_cat`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=35 then 1 ELSE 0 END) AS `total_certified_cas`,

SUM(case when c.status_type_id=1 AND mc.modality_id=1 then 1 ELSE 0 END) AS `total_certified_acupunture`,
SUM(case when c.status_type_id=1 AND mc.modality_id=2 then 1 ELSE 0 END) AS `total_certified_chiropractic`,
SUM(case when c.status_type_id=1 AND mc.modality_id=3 then 1 ELSE 0 END) AS `total_certified_hilot`,
SUM(case when c.status_type_id=1 AND mc.modality_id=4 then 1 ELSE 0 END) AS `total_certified_homeopathy`,
SUM(case when c.status_type_id=1 AND mc.modality_id=5 then 1 ELSE 0 END) AS `total_certified_naturopathy`,
SUM(case when c.status_type_id=1 AND mc.modality_id=6 then 1 ELSE 0 END) AS `total_certified_osteopathy`,
SUM(case when c.status_type_id=1 AND mc.modality_id=7 then 1 ELSE 0 END) AS `total_certified_tcm`,
SUM(case when c.status_type_id=1 AND mc.modality_id=8 then 1 ELSE 0 END) AS `total_certified_tuina`,
SUM(case when c.status_type_id=1 AND mc.modality_id=9 then 1 ELSE 0 END) AS `total_certified_anthroposophic`,
SUM(case when c.status_type_id=1 AND mc.modality_id=10 then 1 ELSE 0 END) AS `total_certified_ayurveda`,

SUM(case when c.status_type_id=1 AND c.modality_class_id=1 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_cma`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=2 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_cama`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=3 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_ca`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=4 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_caa`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=69 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_vap`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=8 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_cch`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=11 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_chp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=36 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_rhp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=12 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_cmh`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=37 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_ch`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=17 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_cmn`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=18 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_cnp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=21 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_co`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=22 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_ctmcp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=39 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_ccmd`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=26 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_catmt`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=27 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_ctmt`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=28 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_cahp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=29 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_caap`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=30 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_caamp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=31 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_camp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=32 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_calp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=33 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_calt`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=34 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_cat`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=35 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_cas`,

SUM(case when c.status_type_id=1 AND mc.modality_id=1 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_acupunture`,
SUM(case when c.status_type_id=1 AND mc.modality_id=2 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_chiropractic`,
SUM(case when c.status_type_id=1 AND mc.modality_id=3 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_hilot`,
SUM(case when c.status_type_id=1 AND mc.modality_id=4 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_homeopathy`,
SUM(case when c.status_type_id=1 AND mc.modality_id=5 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_naturopathy`,
SUM(case when c.status_type_id=1 AND mc.modality_id=6 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_osteopathy`,
SUM(case when c.status_type_id=1 AND mc.modality_id=7 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_tcm`,
SUM(case when c.status_type_id=1 AND mc.modality_id=8 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_tuina`,
SUM(case when c.status_type_id=1 AND mc.modality_id=9 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_anthroposophic`,
SUM(case when c.status_type_id=1 AND mc.modality_id=10 AND p.sex_type_id=1 then 1 ELSE 0 END) AS `total_certified_male_ayurveda`,

SUM(case when c.status_type_id=1 AND c.modality_class_id=1 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_cma`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=2 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_cama`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=3 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_ca`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=4 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_caa`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=69 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_vap`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=8 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_cch`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=11 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_chp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=36 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_rhp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=12 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_cmh`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=37 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_ch`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=17 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_cmn`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=18 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_cnp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=21 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_co`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=22 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_ctmcp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=39 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_ccmd`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=26 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_catmt`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=27 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_ctmt`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=28 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_cahp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=29 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_caap`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=30 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_caamp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=31 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_camp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=32 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_calp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=33 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_calt`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=34 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_cat`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=35 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_cas`,

SUM(case when c.status_type_id=1 AND mc.modality_id=1 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_acupunture`,
SUM(case when c.status_type_id=1 AND mc.modality_id=2 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_chiropractic`,
SUM(case when c.status_type_id=1 AND mc.modality_id=3 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_hilot`,
SUM(case when c.status_type_id=1 AND mc.modality_id=4 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_homeopathy`,
SUM(case when c.status_type_id=1 AND mc.modality_id=5 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_naturopathy`,
SUM(case when c.status_type_id=1 AND mc.modality_id=6 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_osteopathy`,
SUM(case when c.status_type_id=1 AND mc.modality_id=7 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_tcm`,
SUM(case when c.status_type_id=1 AND mc.modality_id=8 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_tuina`,
SUM(case when c.status_type_id=1 AND mc.modality_id=9 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_anthroposophic`,
SUM(case when c.status_type_id=1 AND mc.modality_id=10 AND p.sex_type_id=2 then 1 ELSE 0 END) AS `total_certified_female_ayurveda`,

SUM(case when c.status_type_id=1 AND c.modality_class_id=1 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_cma`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=2 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_cama`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=3 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_ca`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=4 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_caa`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=69 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_vap`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=8 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_cch`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=11 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_chp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=36 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_rhp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=12 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_cmh`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=37 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_ch`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=17 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_cmn`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=18 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_cnp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=21 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_co`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=22 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_ctmcp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=39 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_ccmd`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=26 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_catmt`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=27 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_ctmt`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=28 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_cahp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=29 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_caap`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=30 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_caamp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=31 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_camp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=32 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_calp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=33 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_calt`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=34 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_cat`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=35 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_cas`,

SUM(case when c.status_type_id=1 AND mc.modality_id=1 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_acupunture`,
SUM(case when c.status_type_id=1 AND mc.modality_id=2 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_chiropractic`,
SUM(case when c.status_type_id=1 AND mc.modality_id=3 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_hilot`,
SUM(case when c.status_type_id=1 AND mc.modality_id=4 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_homeopathy`,
SUM(case when c.status_type_id=1 AND mc.modality_id=5 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_naturopathy`,
SUM(case when c.status_type_id=1 AND mc.modality_id=6 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_osteopathy`,
SUM(case when c.status_type_id=1 AND mc.modality_id=7 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_tcm`,
SUM(case when c.status_type_id=1 AND mc.modality_id=8 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_tuina`,
SUM(case when c.status_type_id=1 AND mc.modality_id=9 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_anthroposophic`,
SUM(case when c.status_type_id=1 AND mc.modality_id=10 AND p.primary_citizenship_id=608 then 1 ELSE 0 END) AS `total_certified_filipino_ayurveda`,

SUM(case when c.status_type_id=1 AND c.modality_class_id=1 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_cma`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=2 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_cama`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=3 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_ca`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=4 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_caa`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=69 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_vap`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=8 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_cch`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=11 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_chp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=36 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_rhp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=12 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_cmh`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=37 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_ch`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=17 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_cmn`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=18 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_cnp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=21 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_co`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=22 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_ctmcp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=39 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_ccmd`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=26 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_catmt`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=27 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_ctmt`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=28 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_cahp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=29 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_caap`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=30 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_caamp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=31 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_camp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=32 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_calp`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=33 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_calt`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=34 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_cat`,
SUM(case when c.status_type_id=1 AND c.modality_class_id=35 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_cas`,

SUM(case when c.status_type_id=1 AND mc.modality_id=1 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_acupunture`,
SUM(case when c.status_type_id=1 AND mc.modality_id=2 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_chiropractic`,
SUM(case when c.status_type_id=1 AND mc.modality_id=3 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_hilot`,
SUM(case when c.status_type_id=1 AND mc.modality_id=4 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_homeopathy`,
SUM(case when c.status_type_id=1 AND mc.modality_id=5 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_naturopathy`,
SUM(case when c.status_type_id=1 AND mc.modality_id=6 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_osteopathy`,
SUM(case when c.status_type_id=1 AND mc.modality_id=7 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_tcm`,
SUM(case when c.status_type_id=1 AND mc.modality_id=8 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_tuina`,
SUM(case when c.status_type_id=1 AND mc.modality_id=9 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_anthroposophic`,
SUM(case when c.status_type_id=1 AND mc.modality_id=10 AND p.primary_citizenship_id!=608 then 1 ELSE 0 END) AS `total_certified_foreign_ayurveda`

FROM certifications c
LEFT JOIN practitioners p ON c.practitioner_id=p.id
LEFT JOIN modality_classes mc on c.modality_class_id=mc.id